#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CRUDANDROIDMYSQL_.Resource", IsApplication=true)]

namespace CRUDANDROIDMYSQL_
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f0400b9
			public const int amber100 = 2130968761;
			
			// aapt resource value: 0x7f0400ba
			public const int amber200 = 2130968762;
			
			// aapt resource value: 0x7f0400bb
			public const int amber300 = 2130968763;
			
			// aapt resource value: 0x7f0400bc
			public const int amber400 = 2130968764;
			
			// aapt resource value: 0x7f0400b8
			public const int amber50 = 2130968760;
			
			// aapt resource value: 0x7f0400bd
			public const int amber500 = 2130968765;
			
			// aapt resource value: 0x7f0400be
			public const int amber600 = 2130968766;
			
			// aapt resource value: 0x7f0400bf
			public const int amber700 = 2130968767;
			
			// aapt resource value: 0x7f0400c0
			public const int amber800 = 2130968768;
			
			// aapt resource value: 0x7f0400c1
			public const int amber900 = 2130968769;
			
			// aapt resource value: 0x7f0400c2
			public const int amberA100 = 2130968770;
			
			// aapt resource value: 0x7f0400c3
			public const int amberA200 = 2130968771;
			
			// aapt resource value: 0x7f0400c4
			public const int amberA400 = 2130968772;
			
			// aapt resource value: 0x7f0400c5
			public const int amberA700 = 2130968773;
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f040049
			public const int blue100 = 2130968649;
			
			// aapt resource value: 0x7f04004a
			public const int blue200 = 2130968650;
			
			// aapt resource value: 0x7f04004b
			public const int blue300 = 2130968651;
			
			// aapt resource value: 0x7f04004c
			public const int blue400 = 2130968652;
			
			// aapt resource value: 0x7f040048
			public const int blue50 = 2130968648;
			
			// aapt resource value: 0x7f04004d
			public const int blue500 = 2130968653;
			
			// aapt resource value: 0x7f04004e
			public const int blue600 = 2130968654;
			
			// aapt resource value: 0x7f04004f
			public const int blue700 = 2130968655;
			
			// aapt resource value: 0x7f040050
			public const int blue800 = 2130968656;
			
			// aapt resource value: 0x7f040051
			public const int blue900 = 2130968657;
			
			// aapt resource value: 0x7f040052
			public const int blueA100 = 2130968658;
			
			// aapt resource value: 0x7f040053
			public const int blueA200 = 2130968659;
			
			// aapt resource value: 0x7f040054
			public const int blueA400 = 2130968660;
			
			// aapt resource value: 0x7f040055
			public const int blueA700 = 2130968661;
			
			// aapt resource value: 0x7f0400f7
			public const int blueGrey100 = 2130968823;
			
			// aapt resource value: 0x7f0400f8
			public const int blueGrey200 = 2130968824;
			
			// aapt resource value: 0x7f0400f9
			public const int blueGrey300 = 2130968825;
			
			// aapt resource value: 0x7f0400fa
			public const int blueGrey400 = 2130968826;
			
			// aapt resource value: 0x7f0400f6
			public const int blueGrey50 = 2130968822;
			
			// aapt resource value: 0x7f0400fb
			public const int blueGrey500 = 2130968827;
			
			// aapt resource value: 0x7f0400fc
			public const int blueGrey600 = 2130968828;
			
			// aapt resource value: 0x7f0400fd
			public const int blueGrey700 = 2130968829;
			
			// aapt resource value: 0x7f0400fe
			public const int blueGrey800 = 2130968830;
			
			// aapt resource value: 0x7f0400ff
			public const int blueGrey900 = 2130968831;
			
			// aapt resource value: 0x7f0400e3
			public const int brown100 = 2130968803;
			
			// aapt resource value: 0x7f0400e4
			public const int brown200 = 2130968804;
			
			// aapt resource value: 0x7f0400e5
			public const int brown300 = 2130968805;
			
			// aapt resource value: 0x7f0400e6
			public const int brown400 = 2130968806;
			
			// aapt resource value: 0x7f0400e2
			public const int brown50 = 2130968802;
			
			// aapt resource value: 0x7f0400e7
			public const int brown500 = 2130968807;
			
			// aapt resource value: 0x7f0400e8
			public const int brown600 = 2130968808;
			
			// aapt resource value: 0x7f0400e9
			public const int brown700 = 2130968809;
			
			// aapt resource value: 0x7f0400ea
			public const int brown800 = 2130968810;
			
			// aapt resource value: 0x7f0400eb
			public const int brown900 = 2130968811;
			
			// aapt resource value: 0x7f040065
			public const int cyan100 = 2130968677;
			
			// aapt resource value: 0x7f040066
			public const int cyan200 = 2130968678;
			
			// aapt resource value: 0x7f040067
			public const int cyan300 = 2130968679;
			
			// aapt resource value: 0x7f040068
			public const int cyan400 = 2130968680;
			
			// aapt resource value: 0x7f040064
			public const int cyan50 = 2130968676;
			
			// aapt resource value: 0x7f040069
			public const int cyan500 = 2130968681;
			
			// aapt resource value: 0x7f04006a
			public const int cyan600 = 2130968682;
			
			// aapt resource value: 0x7f04006b
			public const int cyan700 = 2130968683;
			
			// aapt resource value: 0x7f04006c
			public const int cyan800 = 2130968684;
			
			// aapt resource value: 0x7f04006d
			public const int cyan900 = 2130968685;
			
			// aapt resource value: 0x7f04006e
			public const int cyanA100 = 2130968686;
			
			// aapt resource value: 0x7f04006f
			public const int cyanA200 = 2130968687;
			
			// aapt resource value: 0x7f040070
			public const int cyanA400 = 2130968688;
			
			// aapt resource value: 0x7f040071
			public const int cyanA700 = 2130968689;
			
			// aapt resource value: 0x7f0400d5
			public const int deepOrange100 = 2130968789;
			
			// aapt resource value: 0x7f0400d6
			public const int deepOrange200 = 2130968790;
			
			// aapt resource value: 0x7f0400d7
			public const int deepOrange300 = 2130968791;
			
			// aapt resource value: 0x7f0400d8
			public const int deepOrange400 = 2130968792;
			
			// aapt resource value: 0x7f0400d4
			public const int deepOrange50 = 2130968788;
			
			// aapt resource value: 0x7f0400d9
			public const int deepOrange500 = 2130968793;
			
			// aapt resource value: 0x7f0400da
			public const int deepOrange600 = 2130968794;
			
			// aapt resource value: 0x7f0400db
			public const int deepOrange700 = 2130968795;
			
			// aapt resource value: 0x7f0400dc
			public const int deepOrange800 = 2130968796;
			
			// aapt resource value: 0x7f0400dd
			public const int deepOrange900 = 2130968797;
			
			// aapt resource value: 0x7f0400de
			public const int deepOrangeA100 = 2130968798;
			
			// aapt resource value: 0x7f0400df
			public const int deepOrangeA200 = 2130968799;
			
			// aapt resource value: 0x7f0400e0
			public const int deepOrangeA400 = 2130968800;
			
			// aapt resource value: 0x7f0400e1
			public const int deepOrangeA700 = 2130968801;
			
			// aapt resource value: 0x7f04002d
			public const int deepPurple100 = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int deepPurple200 = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int deepPurple300 = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int deepPurple400 = 2130968624;
			
			// aapt resource value: 0x7f04002c
			public const int deepPurple50 = 2130968620;
			
			// aapt resource value: 0x7f040031
			public const int deepPurple500 = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int deepPurple600 = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int deepPurple700 = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int deepPurple800 = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int deepPurple900 = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int deepPurpleA100 = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int deepPurpleA200 = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int deepPurpleA400 = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int deepPurpleA700 = 2130968633;
			
			// aapt resource value: 0x7f040081
			public const int green100 = 2130968705;
			
			// aapt resource value: 0x7f040082
			public const int green200 = 2130968706;
			
			// aapt resource value: 0x7f040083
			public const int green300 = 2130968707;
			
			// aapt resource value: 0x7f040084
			public const int green400 = 2130968708;
			
			// aapt resource value: 0x7f040080
			public const int green50 = 2130968704;
			
			// aapt resource value: 0x7f040085
			public const int green500 = 2130968709;
			
			// aapt resource value: 0x7f040086
			public const int green600 = 2130968710;
			
			// aapt resource value: 0x7f040087
			public const int green700 = 2130968711;
			
			// aapt resource value: 0x7f040088
			public const int green800 = 2130968712;
			
			// aapt resource value: 0x7f040089
			public const int green900 = 2130968713;
			
			// aapt resource value: 0x7f04008a
			public const int greenA100 = 2130968714;
			
			// aapt resource value: 0x7f04008b
			public const int greenA200 = 2130968715;
			
			// aapt resource value: 0x7f04008c
			public const int greenA400 = 2130968716;
			
			// aapt resource value: 0x7f04008d
			public const int greenA700 = 2130968717;
			
			// aapt resource value: 0x7f0400ed
			public const int grey100 = 2130968813;
			
			// aapt resource value: 0x7f0400ee
			public const int grey200 = 2130968814;
			
			// aapt resource value: 0x7f0400ef
			public const int grey300 = 2130968815;
			
			// aapt resource value: 0x7f0400f0
			public const int grey400 = 2130968816;
			
			// aapt resource value: 0x7f0400ec
			public const int grey50 = 2130968812;
			
			// aapt resource value: 0x7f0400f1
			public const int grey500 = 2130968817;
			
			// aapt resource value: 0x7f0400f2
			public const int grey600 = 2130968818;
			
			// aapt resource value: 0x7f0400f3
			public const int grey700 = 2130968819;
			
			// aapt resource value: 0x7f0400f4
			public const int grey800 = 2130968820;
			
			// aapt resource value: 0x7f0400f5
			public const int grey900 = 2130968821;
			
			// aapt resource value: 0x7f04003b
			public const int indigo100 = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int indigo200 = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int indigo300 = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int indigo400 = 2130968638;
			
			// aapt resource value: 0x7f04003a
			public const int indigo50 = 2130968634;
			
			// aapt resource value: 0x7f04003f
			public const int indigo500 = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int indigo600 = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int indigo700 = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int indigo800 = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int indigo900 = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int indigoA100 = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int indigoA200 = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int indigoA400 = 2130968646;
			
			// aapt resource value: 0x7f040047
			public const int indigoA700 = 2130968647;
			
			// aapt resource value: 0x7f040057
			public const int lightBlue100 = 2130968663;
			
			// aapt resource value: 0x7f040058
			public const int lightBlue200 = 2130968664;
			
			// aapt resource value: 0x7f040059
			public const int lightBlue300 = 2130968665;
			
			// aapt resource value: 0x7f04005a
			public const int lightBlue400 = 2130968666;
			
			// aapt resource value: 0x7f040056
			public const int lightBlue50 = 2130968662;
			
			// aapt resource value: 0x7f04005b
			public const int lightBlue500 = 2130968667;
			
			// aapt resource value: 0x7f04005c
			public const int lightBlue600 = 2130968668;
			
			// aapt resource value: 0x7f04005d
			public const int lightBlue700 = 2130968669;
			
			// aapt resource value: 0x7f04005e
			public const int lightBlue800 = 2130968670;
			
			// aapt resource value: 0x7f04005f
			public const int lightBlue900 = 2130968671;
			
			// aapt resource value: 0x7f040060
			public const int lightBlueA100 = 2130968672;
			
			// aapt resource value: 0x7f040061
			public const int lightBlueA200 = 2130968673;
			
			// aapt resource value: 0x7f040062
			public const int lightBlueA400 = 2130968674;
			
			// aapt resource value: 0x7f040063
			public const int lightBlueA700 = 2130968675;
			
			// aapt resource value: 0x7f04008f
			public const int lightGreen100 = 2130968719;
			
			// aapt resource value: 0x7f040090
			public const int lightGreen200 = 2130968720;
			
			// aapt resource value: 0x7f040091
			public const int lightGreen300 = 2130968721;
			
			// aapt resource value: 0x7f040092
			public const int lightGreen400 = 2130968722;
			
			// aapt resource value: 0x7f04008e
			public const int lightGreen50 = 2130968718;
			
			// aapt resource value: 0x7f040093
			public const int lightGreen500 = 2130968723;
			
			// aapt resource value: 0x7f040094
			public const int lightGreen600 = 2130968724;
			
			// aapt resource value: 0x7f040095
			public const int lightGreen700 = 2130968725;
			
			// aapt resource value: 0x7f040096
			public const int lightGreen800 = 2130968726;
			
			// aapt resource value: 0x7f040097
			public const int lightGreen900 = 2130968727;
			
			// aapt resource value: 0x7f040098
			public const int lightGreenA100 = 2130968728;
			
			// aapt resource value: 0x7f040099
			public const int lightGreenA200 = 2130968729;
			
			// aapt resource value: 0x7f04009a
			public const int lightGreenA400 = 2130968730;
			
			// aapt resource value: 0x7f04009b
			public const int lightGreenA700 = 2130968731;
			
			// aapt resource value: 0x7f04009d
			public const int lime100 = 2130968733;
			
			// aapt resource value: 0x7f04009e
			public const int lime200 = 2130968734;
			
			// aapt resource value: 0x7f04009f
			public const int lime300 = 2130968735;
			
			// aapt resource value: 0x7f0400a0
			public const int lime400 = 2130968736;
			
			// aapt resource value: 0x7f04009c
			public const int lime50 = 2130968732;
			
			// aapt resource value: 0x7f0400a1
			public const int lime500 = 2130968737;
			
			// aapt resource value: 0x7f0400a2
			public const int lime600 = 2130968738;
			
			// aapt resource value: 0x7f0400a3
			public const int lime700 = 2130968739;
			
			// aapt resource value: 0x7f0400a4
			public const int lime800 = 2130968740;
			
			// aapt resource value: 0x7f0400a5
			public const int lime900 = 2130968741;
			
			// aapt resource value: 0x7f0400a6
			public const int limeA100 = 2130968742;
			
			// aapt resource value: 0x7f0400a7
			public const int limeA200 = 2130968743;
			
			// aapt resource value: 0x7f0400a8
			public const int limeA400 = 2130968744;
			
			// aapt resource value: 0x7f0400a9
			public const int limeA700 = 2130968745;
			
			// aapt resource value: 0x7f0400c7
			public const int orange100 = 2130968775;
			
			// aapt resource value: 0x7f0400c8
			public const int orange200 = 2130968776;
			
			// aapt resource value: 0x7f0400c9
			public const int orange300 = 2130968777;
			
			// aapt resource value: 0x7f0400ca
			public const int orange400 = 2130968778;
			
			// aapt resource value: 0x7f0400c6
			public const int orange50 = 2130968774;
			
			// aapt resource value: 0x7f0400cb
			public const int orange500 = 2130968779;
			
			// aapt resource value: 0x7f0400cc
			public const int orange600 = 2130968780;
			
			// aapt resource value: 0x7f0400cd
			public const int orange700 = 2130968781;
			
			// aapt resource value: 0x7f0400ce
			public const int orange800 = 2130968782;
			
			// aapt resource value: 0x7f0400cf
			public const int orange900 = 2130968783;
			
			// aapt resource value: 0x7f0400d0
			public const int orangeA100 = 2130968784;
			
			// aapt resource value: 0x7f0400d1
			public const int orangeA200 = 2130968785;
			
			// aapt resource value: 0x7f0400d2
			public const int orangeA400 = 2130968786;
			
			// aapt resource value: 0x7f0400d3
			public const int orangeA700 = 2130968787;
			
			// aapt resource value: 0x7f040011
			public const int pink100 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int pink200 = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int pink300 = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int pink400 = 2130968596;
			
			// aapt resource value: 0x7f040010
			public const int pink50 = 2130968592;
			
			// aapt resource value: 0x7f040015
			public const int pink500 = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int pink600 = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int pink700 = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int pink800 = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int pink900 = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int pinkA100 = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int pinkA200 = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int pinkA400 = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int pinkA700 = 2130968605;
			
			// aapt resource value: 0x7f04001f
			public const int purple100 = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int purple200 = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int purple300 = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int purple400 = 2130968610;
			
			// aapt resource value: 0x7f04001e
			public const int purple50 = 2130968606;
			
			// aapt resource value: 0x7f040023
			public const int purple500 = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int purple600 = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int purple700 = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int purple800 = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int purple900 = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int purpleA100 = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int purpleA200 = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int purpleA400 = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int purpleA700 = 2130968619;
			
			// aapt resource value: 0x7f040003
			public const int red100 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int red200 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int red300 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int red400 = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int red50 = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int red500 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int red600 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int red700 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int red800 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int red900 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int redA100 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int redA200 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int redA400 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int redA700 = 2130968591;
			
			// aapt resource value: 0x7f040073
			public const int teal100 = 2130968691;
			
			// aapt resource value: 0x7f040074
			public const int teal200 = 2130968692;
			
			// aapt resource value: 0x7f040075
			public const int teal300 = 2130968693;
			
			// aapt resource value: 0x7f040076
			public const int teal400 = 2130968694;
			
			// aapt resource value: 0x7f040072
			public const int teal50 = 2130968690;
			
			// aapt resource value: 0x7f040077
			public const int teal500 = 2130968695;
			
			// aapt resource value: 0x7f040078
			public const int teal600 = 2130968696;
			
			// aapt resource value: 0x7f040079
			public const int teal700 = 2130968697;
			
			// aapt resource value: 0x7f04007a
			public const int teal800 = 2130968698;
			
			// aapt resource value: 0x7f04007b
			public const int teal900 = 2130968699;
			
			// aapt resource value: 0x7f04007c
			public const int tealA100 = 2130968700;
			
			// aapt resource value: 0x7f04007d
			public const int tealA200 = 2130968701;
			
			// aapt resource value: 0x7f04007e
			public const int tealA400 = 2130968702;
			
			// aapt resource value: 0x7f04007f
			public const int tealA700 = 2130968703;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			// aapt resource value: 0x7f0400ab
			public const int yellow100 = 2130968747;
			
			// aapt resource value: 0x7f0400ac
			public const int yellow200 = 2130968748;
			
			// aapt resource value: 0x7f0400ad
			public const int yellow300 = 2130968749;
			
			// aapt resource value: 0x7f0400ae
			public const int yellow400 = 2130968750;
			
			// aapt resource value: 0x7f0400aa
			public const int yellow50 = 2130968746;
			
			// aapt resource value: 0x7f0400af
			public const int yellow500 = 2130968751;
			
			// aapt resource value: 0x7f0400b0
			public const int yellow600 = 2130968752;
			
			// aapt resource value: 0x7f0400b1
			public const int yellow700 = 2130968753;
			
			// aapt resource value: 0x7f0400b2
			public const int yellow800 = 2130968754;
			
			// aapt resource value: 0x7f0400b3
			public const int yellow900 = 2130968755;
			
			// aapt resource value: 0x7f0400b4
			public const int yellowA100 = 2130968756;
			
			// aapt resource value: 0x7f0400b5
			public const int yellowA200 = 2130968757;
			
			// aapt resource value: 0x7f0400b6
			public const int yellowA400 = 2130968758;
			
			// aapt resource value: 0x7f0400b7
			public const int yellowA700 = 2130968759;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int baseline_delete_forever_black_18dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int baseline_edit_black_18dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int delete = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int select_ = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int update = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int user = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int btCad = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int btVoltar = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int btlogin = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int campoEmail = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int campoLogin = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int campoNome = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int campoSenha = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int create = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int delete = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int imDel = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int imgDel = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int imgEdit = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int lvsSelect = 2131165200;
			
			// aapt resource value: 0x7f070008
			public const int select = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int txtId = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int txtNome = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int update = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Create = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LOGIN = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MENU = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ModeloListView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Select = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060003
			public const int acesso = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int create = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int create_f = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int create_m = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int create_sexo = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int delete = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int menu = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int nome = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int select = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int senha = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int update = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int usuario = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int create = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int login = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int menu = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
